---
- name: List user names
  hosts: gcp_vms
  become: yes
  tasks:
    - name: Get list of user names
      command: "cut -d: -f1 /etc/passwd"
      register: user_list

    - name: Display user names
      debug:
        msg: "{{ user_list.stdout_lines }}"

