---
- name: Create multiple users on GCP VM
  hosts: gcp_vms
  become: yes
  tasks:
    - name: Create users with passwords
      user:
        name: "{{ item.name }}"
        state: present
        password: "{{ item.password | password_hash('sha512') }}"
        create_home: yes
        shell: /bin/bash
      loop:
        - { name: user1, password: 'password1' }
        - { name: user2, password: 'password2' }
        - { name: user3, password: 'password3' }
        - { name: user4, password: 'password4' }
        - { name: user5, password: 'password5' }
        - { name: user6, password: 'password6' }
        - { name: user7, password: 'password7' }
        - { name: user8, password: 'password8' }
        - { name: user9, password: 'password9' }
        - { name: user10, password: 'password10' }

